Document Sigstore's graduated application to the OpenSSF
sigstore/TSC pull request #48
Opened 2024-02-19 19:18 UTC by bobcallaway

This represents a voting item for the Sigstore TSC, which is to formally document how the TSC believes we meet the criteria for an OpenSSF graduated project.

Since this is a voting item, it needs an explicit vote from all members of @sigstore/core-team.

Once approved, @lukehinds has agreed to convert this into the required documents and process as specified at https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#graduated for discussion and vote at a future OpenSSF TAC meeting.

2024-02-20 07:06 UTC, lukehinds approved these changes

2024-02-20 17:58 UTC, SantiagoTorres submitted a review, later dismissed

2024-02-20 17:58 UTC, SantiagoTorres commented on docs/best_practices_badge.md
> +Sigstore is an open source project for improving software supply chain security. The Sigstore framework and tooling empowers software developers and consumers to securely sign and verify software art
would it have been worth mentioning SLSA prov + in-toto attestations here?

2024-02-20 18:43 UTC, priyawadhwa submitted a review, later dismissed
lgtm! thanks for writing this up @bobcallaway.

2024-02-20 20:20 UTC, trevrosen requested changes
I have just a few requested changes. Overall this looks great - thanks so much for taking the time here, @bobcallaway!

2024-02-20 20:20 UTC, trevrosen commented on docs/best_practices_badge.md
> +This is a general principle within sigstore, with evidence present across our repositories.
Capitalize "Sigstore"

2024-02-20 20:20 UTC, trevrosen commented on docs/best_practices_badge.md
> +This is a general principle within sigstore, with evidence present across our repositories.
Capitalize "Sigstore"

2024-02-20 20:20 UTC, trevrosen commented on docs/best_practices_badge.md
> +Several of our maintainers work in security engineering departments (e.g. Google’s Open Source Security Team).
Plz add "GitHub's Package Security Team" to the `e.g.` here 😃

2024-02-20 20:20 UTC, trevrosen commented on docs/best_practices_badge.md
> +Several of our maintainers work in security engineering departments (e.g. Google’s Open Source Security Team).
See above 😄

2024-02-20 20:20 UTC, trevrosen commented on docs/openssf_graduated_application.md
> +      - Maintainers from: Alibaba, Google, Red Hat, Stacklok, SUSE, Stacklok 
Stacklok is listed 2x

2024-02-20 22:20 UTC, trevrosen approved these changes

2024-02-21 15:23 UTC, SantiagoTorres approved these changes

2024-02-21 19:00 UTC, lukehinds approved these changes

2024-02-28 18:00 UTC, merged